language: android
sudo: required
jdk: oraclejdk7
    components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-27.0.0

    # The SDK version used to compile your project
    - android-26
    
before_install:
- chmod +x gradlew

before_script:
- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &


script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
